import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Unique Suite — source: src/main.js + unique-core + unique-agenda-core + calendar-original
https://github.com/Benhaman9/unique-suite
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.js"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  platform: "browser",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  mkdirSync("release", { recursive: true });
  copyFileSync("main.js", "release/main.js");
  copyFileSync("manifest.json", "release/manifest.json");
  copyFileSync("styles.css", "release/styles.css");
  process.exit(0);
} else {
  await context.watch();
}
